[2024-08-23T23:05:32.397+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.scale_data manual__2024-08-23T23:04:46.957262+00:00 [queued]>
[2024-08-23T23:05:32.409+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.scale_data manual__2024-08-23T23:04:46.957262+00:00 [queued]>
[2024-08-23T23:05:32.410+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-08-23T23:05:32.427+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): scale_data> on 2024-08-23 23:04:46.957262+00:00
[2024-08-23T23:05:32.440+0000] {standard_task_runner.py:60} INFO - Started process 681 to run task
[2024-08-23T23:05:32.442+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl', 'scale_data', 'manual__2024-08-23T23:04:46.957262+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl_process.py', '--cfg-path', '/tmp/tmp5e2ag9eg']
[2024-08-23T23:05:32.445+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask scale_data
[2024-08-23T23:05:32.507+0000] {task_command.py:423} INFO - Running <TaskInstance: etl.scale_data manual__2024-08-23T23:04:46.957262+00:00 [running]> on host 38dd9e071e17
[2024-08-23T23:05:32.616+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='scale_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-23T23:04:46.957262+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-23T23:04:46.957262+00:00'
[2024-08-23T23:05:32.618+0000] {etl_process.py:287} INFO - Leyendo Datos
[2024-08-23T23:05:32.636+0000] {etl_process.py:294} INFO - Datos Leidos
[2024-08-23T23:05:32.665+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-08-23T23:05:32.994+0000] {configprovider.py:958} INFO - Found endpoint for s3 via: environment_service.
[2024-08-23T23:05:33.046+0000] {etl_process.py:329} INFO - X_train_scaled guardado en PostgreSQL en la tabla: X_train_scaled
[2024-08-23T23:05:33.047+0000] {etl_process.py:330} INFO - X_train_scaled en XCOM con key: X_train_scaled
[2024-08-23T23:05:33.590+0000] {etl_process.py:334} INFO - X_test_scaled guardado en PostgreSQL en la tabla: X_test_scaled
[2024-08-23T23:05:33.591+0000] {etl_process.py:335} INFO - X_test_scaled en XCOM con key: X_test_scaled
[2024-08-23T23:05:33.753+0000] {etl_process.py:339} INFO - y_train_scaled guardado en PostgreSQL en la tabla: y_train_scaled
[2024-08-23T23:05:33.754+0000] {etl_process.py:340} INFO - y_train_scaled en XCOM con key: y_train_scaled
[2024-08-23T23:05:33.889+0000] {etl_process.py:344} INFO - y_test_scaled guardado en PostgreSQL en la tabla: y_test_scaled
[2024-08-23T23:05:33.890+0000] {etl_process.py:345} INFO - y_test_scaled en XCOM con key: y_test_scaled
[2024-08-23T23:05:34.056+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-08-23T23:05:34.070+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl, task_id=scale_data, execution_date=20240823T230446, start_date=20240823T230532, end_date=20240823T230534
[2024-08-23T23:05:34.146+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-08-23T23:05:34.171+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
